title: Cheney Elementary PTA®
description: Quick resources for Cheney Elementary families and new parents.
description_es: Recursos rápidos para las familias de Cheney Elementary y los padres nuevos.
url: "https://cheneypta.org"
baseurl: ""

markdown: kramdown
permalink: pretty

collections:
  resources:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "resources"
    values:
      layout: resource

include:
  - .well-known

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
