title: Cheney Elementary PTA®
description: Cheney Elementary PTA resources, events, volunteer opportunities and family information for the Orlando, Florida school community.
description_es: Recursos, eventos, oportunidades de voluntariado e información familiar de Cheney Elementary PTA para la comunidad escolar de Orlando, Florida.
url: "https://cheneypta.org"
baseurl: ""

markdown: kramdown
permalink: pretty

collections:
  resources:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "resources"
    values:
      layout: resource

include:
  - .well-known

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
